url: https://kviktor-96.github.io/220doma.ru/
baseurl: /220doma.ru/

# Site settings
title: 220doma.ru
email: info@220doma.ru
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: "Кузин Виктор"
  pic: 1.webp
  position: Инженер-электрик
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2.webp
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3.webp
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: vk
    url: https://vk.com/kuzin.kuzin
  - title: instagram
    url: https://instagram.com/220doma.ru
  - title: whatsapp
    url: https://wa.me/+79003587669
  - title: telegram
    url: https://t.me/kuzvikal
    

# Postal address (add as many lines as necessary)
address:
  - line: Брянск

# Build settings
markdown: kramdown
permalink: pretty
